#!/usr/bin/env python
"""From-scratch NumPy reproduction of pykurucz's two SPECIAL line-opacity types,
verified to machine precision against reference/linetypes.npz:

  TYPE=1   autoionizing lines      -> the ashore/bshore Fano-shore Lorentzian
  TYPE=81  merged-continuum lines  -> the linear ramp into the continuum
           (and TYPE=80 / any code>3, which pykurucz routes identically)

These are the two line families that Lecture 5's ASYNTH Voigt accumulation does
NOT handle.  They are produced by pykurucz in:

  synthe_py/engine/opacity.py
    _accumulate_autoionizing_profile   (dispatched for Fort19WingType.AUTOIONIZING)
    _accumulate_merged_continuum       (dispatched for Fort19WingType.CONTINUUM,
                                        i.e. line_type code > 3)

THE TEST WINDOW.  pykurucz's own synthesis was run on a hot star (Teff=12000 K,
logg=4.0, vturb=2) over 188-670 nm (vacuum).  In that synthesis the two routines
genuinely clear the opacity cutoff and deposit opacity:
  * TYPE=1  : Al I autoionizing lines at 193.227 / 193.646 nm (ground state).
  * TYPE=81 : He I / He II / H I merged-continuum lines at 205.06, 260.05,
              312.18, 342.19, 364.55, 364.70, 367.98, 569.62, 663.40 nm
              (plus Al I TYPE=80 merged continuum at 207.13 / 207.61 nm).
The 500-510 nm solar window of Lecture 5 contains no such line, which is why the
gap was invisible there.

GROUND TRUTH.  reference/linetypes.npz holds, per contributing (line, depth)
record, the exact INPUTS the leaf routine received (center index, line
wavelength, kappa0/kappa, the damping/shore constants, wmerge/wtail, cutoff, and
the wavelength + continuum slices it reads) and the OUTPUT opacity DELTA pykurucz
deposited into the buffer.  The reference was generated by driving pykurucz's
OWN run_synthesis and recording every call to the two leaf routines (the routines
ran UNMODIFIED).  See _pipeline/gen_linetypes_reference.py.

THIS SCRIPT.  recomputes each DELTA from the stored INPUTS using only NumPy --
the profile formulas transcribed from opacity.py -- and compares to pykurucz's
recorded DELTA.  No pykurucz import; the reference is loaded only as the
comparison ground truth.

Exact formulas (opacity.py, verbatim):

  autoionizing  (per grid point at offset from the line center):
      freq        = C_LIGHT_CM / (lambda * NM_TO_CM)
      freq_center = C_LIGHT_CM / (line_wavelength * NM_TO_CM)
      gamma  = max(|gamma_rad|, 1e-30)
      ashore = gamma_stark
      bshore = gamma_vdw   (-> 1e-30 if |gamma_vdw| < 1e-30)
      eps    = 2 * (freq - freq_center) / gamma
      value  = kappa0 * (ashore*eps + bshore) / (eps*eps + 1) / bshore
      center point deposits kappa0 unconditionally (after the gate below);
      a side stops when value <= 0 or value < continuum[idx]*cutoff.
      Gate: skip the whole line if kappa0 < continuum[center]*cutoff or kappa0<=0.

  merged continuum (idx running from the line center to the tail):
      idx_start = max(center_index, 0)
      idx_merge = searchsorted(wl, merge_wavelength, 'left')
      idx_tail  = min(searchsorted(wl, tail_wavelength, 'right'), n)
      denom     = max(idx_tail - max(idx_merge, idx_start), 1)
      per idx in [idx_start, idx_tail):  skip if wl[idx] < line_wavelength
          value = kappa
          if idx >= idx_merge:  value *= max(idx_tail - idx, 0) / denom
          break the loop if value < continuum[idx]*cutoff, else deposit value.
"""
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
REF = ROOT / "reference"

# Physical constants (synthe_py/engine/opacity.py lines 45-50).
C_LIGHT_CM = 2.99792458e10  # cm / s
NM_TO_CM = 1.0e-7

PASS_TOL = 1e-9  # machine-precision target on max relative error


# ---------------------------------------------------------------------------
# From-scratch reproductions of the two leaf routines, operating on the stored
# per-record slices.  Global grid indices are mapped to slice-local indices via
# `slice_lo`; the routines' control flow is transcribed verbatim from opacity.py.
# ---------------------------------------------------------------------------
def autoionizing_delta(wl, cont, slice_lo, center_index, line_wavelength,
                       kappa0, gamma_rad, gamma_stark, gamma_vdw, cutoff):
    """Reproduce _accumulate_autoionizing_profile over a stored slice."""
    n = wl.size
    delta = np.zeros(n, dtype=np.float64)
    c = center_index - slice_lo  # slice-local center

    center_cutoff = cont[c] * cutoff
    if kappa0 < center_cutoff or kappa0 <= 0.0:
        return delta  # gate: routine returns False, deposits nothing

    freq_center = C_LIGHT_CM / (line_wavelength * NM_TO_CM)
    gamma = max(abs(gamma_rad), 1e-30)
    ashore = gamma_stark
    bshore = gamma_vdw
    if abs(bshore) < 1e-30:
        bshore = 1e-30

    delta[c] += kappa0

    red_active = blue_active = True
    offset = 1
    max_steps = max(c, n - c - 1)
    while offset <= max_steps and (red_active or blue_active):
        if red_active:
            idx = c + offset
            if idx >= n:
                red_active = False
            else:
                freq = C_LIGHT_CM / (wl[idx] * NM_TO_CM)
                eps = 2.0 * (freq - freq_center) / gamma
                value = kappa0 * (ashore * eps + bshore) / (eps * eps + 1.0) / bshore
                if value <= 0.0 or value < cont[idx] * cutoff:
                    red_active = False
                else:
                    delta[idx] += value
        if blue_active:
            idx = c - offset
            if idx < 0:
                blue_active = False
            else:
                freq = C_LIGHT_CM / (wl[idx] * NM_TO_CM)
                eps = 2.0 * (freq - freq_center) / gamma
                value = kappa0 * (ashore * eps + bshore) / (eps * eps + 1.0) / bshore
                if value <= 0.0 or value < cont[idx] * cutoff:
                    blue_active = False
                else:
                    delta[idx] += value
        offset += 1
    return delta


def merged_continuum_delta(wl, cont, slice_lo, line_wavelength, kappa, cutoff,
                           idx_start_g, idx_merge_g, idx_tail_g):
    """Reproduce _accumulate_merged_continuum over a stored slice.

    The routine's ramp uses GLOBAL indices from searchsorted over the full grid.
    Those global indices (idx_start/idx_merge/idx_tail) were recorded with the
    reference, so here the ramp `denom` and the `idx >= idx_merge` test use the
    GLOBAL index, while array reads are translated to the stored slice via
    `slice_lo`.  This reproduces the routine exactly without re-running
    searchsorted on the (truncated) shipped slice.
    """
    n = wl.size
    delta = np.zeros(n, dtype=np.float64)
    if kappa <= 0.0:
        return delta
    if idx_tail_g <= idx_start_g:
        return delta

    denom = max(idx_tail_g - max(idx_merge_g, idx_start_g), 1)

    for idx_g in range(idx_start_g, idx_tail_g):
        loc = idx_g - slice_lo            # slice-local position
        if loc < 0 or loc >= n:
            # Outside the stored slice: such indices are pre-merge flat points
            # that lie below the line center; the real routine deposits opacity
            # only on the stored span (verified: the slice covers every nonzero
            # deposit), so they contribute nothing to the comparison.
            continue
        wave = wl[loc]
        if wave < line_wavelength:
            continue
        value = kappa
        if idx_g >= idx_merge_g:
            value *= max(idx_tail_g - idx_g, 0) / denom
        if value < cont[loc] * cutoff:
            break
        delta[loc] += value
    return delta


# ---------------------------------------------------------------------------
# Verification driver.
# ---------------------------------------------------------------------------
def _relerr(mine, ref):
    """Max relative error on the union of nonzero points."""
    mine = np.asarray(mine, dtype=np.float64)
    ref = np.asarray(ref, dtype=np.float64)
    denom = np.where(np.abs(ref) > 0.0, np.abs(ref), 1.0)
    rel = np.abs(mine - ref) / denom
    return rel


def verify_type(d, prefix, label, scalar_keys):
    n = int(d[f"{prefix}_n"])
    worst_rel = 0.0
    worst_abs = 0.0
    total_pts = 0
    nonzero_recs = 0
    n_match_exact = 0
    wls = set()
    for i in range(n):
        slice_lo = int(d[f"{prefix}{i}_slice_lo"])
        wl = d[f"{prefix}{i}_wl_slice"]
        cont = d[f"{prefix}{i}_cont_slice"]
        ref = d[f"{prefix}{i}_delta_vals"]
        scal = {k: float(d[f"{prefix}{i}_{k}"]) for k in scalar_keys}
        ci = int(scal["center_index"])
        wls.add(round(scal["line_wavelength"], 3))

        if prefix == "auto":
            mine = autoionizing_delta(
                wl, cont, slice_lo, ci, scal["line_wavelength"],
                scal["kappa0"], scal["gamma_rad"], scal["gamma_stark"],
                scal["gamma_vdw"], scal["cutoff"])
        else:
            mine = merged_continuum_delta(
                wl, cont, slice_lo, scal["line_wavelength"], scal["kappa"],
                scal["cutoff"],
                int(d[f"{prefix}{i}_idx_start_g"]),
                int(d[f"{prefix}{i}_idx_merge_g"]),
                int(d[f"{prefix}{i}_idx_tail_g"]))

        rel = _relerr(mine, ref)
        worst_rel = max(worst_rel, float(rel.max()))
        worst_abs = max(worst_abs, float(np.abs(mine - ref).max()))
        total_pts += int(np.count_nonzero(ref))
        nonzero_recs += 1
        if np.array_equal(mine, ref):
            n_match_exact += 1

    print(f"\n{label}")
    print(f"  records compared           : {nonzero_recs}")
    print(f"  distinct line wavelengths  : {sorted(wls)}")
    print(f"  total opacity points       : {total_pts}")
    print(f"  bit-exact records          : {n_match_exact}/{nonzero_recs}")
    print(f"  max |absolute error|       : {worst_abs:.3e}")
    print(f"  max  relative error        : {worst_rel:.3e}")
    return worst_rel, (n_match_exact == nonzero_recs)


def main():
    ref_path = REF / "linetypes.npz"
    if not ref_path.exists():
        sys.exit(f"missing reference {ref_path}; run _pipeline/gen_linetypes_reference.py")
    d = np.load(ref_path)

    teff, logg = d["teff_logg"]
    w0, w1, res = d["window"]
    print("=" * 70)
    print("Special line opacity: TYPE=1 (autoionizing) + TYPE=81 (merged cont.)")
    print("computed from scratch (NumPy) vs pykurucz ground truth")
    print(f"  test star  : Teff={teff:.0f} K  logg={logg:.2f}")
    print(f"  window     : {w0:.1f}-{w1:.1f} nm (vacuum)  R={res:.0f}")
    print("=" * 70)

    auto_keys = ["center_index", "line_wavelength", "kappa0", "gamma_rad",
                 "gamma_stark", "gamma_vdw", "cutoff"]
    cont_keys = ["center_index", "line_wavelength", "kappa", "cutoff",
                 "merge_wavelength", "tail_wavelength"]

    rel_auto, bit_auto = verify_type(
        d, "auto", "TYPE=1  autoionizing  (ashore/bshore shore-Lorentzian)",
        auto_keys)
    rel_cont, bit_cont = verify_type(
        d, "cont", "TYPE=81 merged continuum  (ramp into the continuum)",
        cont_keys)

    worst = max(rel_auto, rel_cont)
    all_bit = bit_auto and bit_cont
    print("\n" + "=" * 70)
    print(f"worst max relative error over both types = {worst:.3e}")
    print(f"all records bit-exact                    = {all_bit}")
    if worst < PASS_TOL:
        print(f"PASS: max relative error < {PASS_TOL:.0e} "
              f"(both special line types reproduced to machine precision)")
        print("=" * 70)
        sys.exit(0)
    else:
        print(f"FAIL: max relative error {worst:.3e} >= {PASS_TOL:.0e}")
        print("=" * 70)
        sys.exit(1)


if __name__ == "__main__":
    main()
