#!/usr/bin/env python3
"""Build canonical chapter sources, the web registry, and rendered products."""

from __future__ import annotations

import argparse
import html
import importlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from book.registry import AFFILIATION, AUTHOR, BY_NUMBER, PARTS  # noqa: E402


def web_registry() -> dict:
    """Return the reader manifest from the canonical Python registry."""

    return {
        "title": "Stellar Spectroscopy from Scratch",
        "series": "A self-contained executable course in stellar atmosphere and synthesis physics",
        "parts": [
            {
                "name": f"Part {part.number}",
                "title": part.title,
                "blurb": part.description,
                "chapters": [
                    {
                        "n": chapter.number,
                        "slug": chapter.slug,
                        "type": "html" if chapter.available else "planned",
                        "available": chapter.available,
                        "title": chapter.title,
                        "lecturer": AUTHOR,
                        "affil": AFFILIATION,
                    }
                    for chapter in part.chapters
                ],
            }
            for part in PARTS
        ],
    }


def write_web_registry() -> Path:
    """Generate the JavaScript reader manifest."""

    output_path = REPOSITORY_ROOT / "assets" / "book-data.js"
    payload = json.dumps(web_registry(), indent=2, ensure_ascii=False)
    output_path.write_text(
        "/* Generated by scripts/build_book.py from book/registry.py. */\n"
        f"window.BOOK = {payload};\n\n"
        "window.BOOK.flat = window.BOOK.parts.flatMap(part =>\n"
        "  part.chapters.map(chapter => ({ ...chapter, part }))\n"
        ");\n"
        "window.BOOK.available = window.BOOK.flat.filter(chapter => chapter.available);\n"
        "window.BOOK.byN = Object.fromEntries(\n"
        "  window.BOOK.flat.map(chapter => [chapter.n, chapter])\n"
        ");\n",
        encoding="utf-8",
    )
    return output_path


def build_chapter(number: int, *, execute: bool) -> tuple[Path, Path]:
    """Generate, optionally execute, and render one available chapter."""

    chapter = BY_NUMBER[number]
    if not chapter.available:
        raise SystemExit(f"chapter {number} is registered but not yet available")
    module = importlib.import_module(f"book.chapters.{chapter.module}")
    document = module.build_notebook()

    content_dir = REPOSITORY_ROOT / "content"
    content_dir.mkdir(parents=True, exist_ok=True)
    notebook_path = content_dir / f"{chapter.slug}.ipynb"
    notebook_path.write_text(
        json.dumps(document, indent=1, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    if execute:
        jupyter_command = shutil.which("jupyter")
        if jupyter_command is None:
            raise SystemExit(
                "Jupyter is required to execute chapters; install it or make "
                "the `jupyter` command available on PATH"
            )
        environment = os.environ.copy()
        matplotlib_cache = REPOSITORY_ROOT / ".cache" / "matplotlib"
        numba_cache = REPOSITORY_ROOT / ".cache" / "numba"
        matplotlib_cache.mkdir(parents=True, exist_ok=True)
        numba_cache.mkdir(parents=True, exist_ok=True)
        environment.setdefault("MPLCONFIGDIR", str(matplotlib_cache))
        environment.setdefault("NUMBA_CACHE_DIR", str(numba_cache))
        environment.setdefault("PYTHONDONTWRITEBYTECODE", "1")
        subprocess.run(
            [
                jupyter_command,
                "nbconvert",
                "--to",
                "notebook",
                "--execute",
                "--inplace",
                "--ExecutePreprocessor.timeout=900",
                "--ExecutePreprocessor.kernel_name=python3",
                str(notebook_path),
            ],
            cwd=REPOSITORY_ROOT,
            env=environment,
            check=True,
        )

    html_path = content_dir / f"{chapter.slug}.html"
    subprocess.run(
        [
            "node",
            str(REPOSITORY_ROOT / "scripts" / "render_fragment.js"),
            str(notebook_path),
            str(html_path),
            str(number),
            html.escape(chapter.title),
            AUTHOR,
            html.escape(AFFILIATION),
        ],
        cwd=REPOSITORY_ROOT,
        check=True,
    )
    return notebook_path, html_path


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser()
    parser.add_argument("chapters", nargs="*", type=int)
    parser.add_argument(
        "--no-execute",
        action="store_true",
        help="generate and render without running code cells",
    )
    parser.add_argument(
        "--registry-only",
        action="store_true",
        help="regenerate only assets/book-data.js",
    )
    return parser.parse_args()


def main() -> None:
    """Run the canonical book build."""

    arguments = parse_args()
    registry_path = write_web_registry()
    print(f"wrote {registry_path.relative_to(REPOSITORY_ROOT)}")
    if arguments.registry_only:
        return

    numbers = arguments.chapters or [
        chapter.number
        for part in PARTS
        for chapter in part.chapters
        if chapter.available
    ]
    for number in numbers:
        if number not in BY_NUMBER:
            raise SystemExit(f"unknown chapter number: {number}")
        notebook_path, html_path = build_chapter(
            number,
            execute=not arguments.no_execute,
        )
        print(
            f"built {notebook_path.relative_to(REPOSITORY_ROOT)} -> "
            f"{html_path.relative_to(REPOSITORY_ROOT)}"
        )


if __name__ == "__main__":
    main()
